name = "GLMCopula"
uuid = "e1188d9a-b146-567e-aa2b-a46eb542ab6f"
keywords = ["copula", "GLM"]
authors = ["Sarah Ji", "Janet Sinsheimer", "Hua Zhou", "Kenneth Lange"]
version = "0.0.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools", "Gurobi", "InteractiveUtils", "Profile", "Random", "RDatasets"]
